#!/usr/bin/env python
"""
@package florence
SDN security test framework top level script
"""

from __future__ import print_function

import sys
import logging
import unittest
import time
import os
import imp
import random
import signal
import fnmatch
import copy

# Set the required path variables for Florence
ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
LIB_DIR = os.path.join(ROOT_DIR, 'lib')
SRC_DIR = os.path.join(ROOT_DIR, 'src')
if os.path.exists(os.path.join(SRC_DIR, 'florence')):
    # Running from source tree
    sys.path.insert(0, SRC_DIR)
    sys.path.insert(0, LIB_DIR)

import oftest.ofutils
import loxi
from florence import config
import florence.setup as setup

# Setup global configuration
(new_config, args) = setup.florence_arg_setup()
config.update(new_config)
setup.logging_setup()
setup.xunit_setup()

if os.getuid() != 0 and not config["allow_user"]:
    setup.die("Super-user privileges required. Please re-run with sudo or as root.")
    sys.exit(1)

# Generate the test suite
suite = unittest.TestSuite()

#TODO Pick an OpenFlow protocol module based on the configured version
name_to_version = dict((v,k) for k, v in loxi.version_names.iteritems())
sys.modules["ofp"] = loxi.protocol(name_to_version[config["openflow_version"]])

# HACK: testutils.py imports controller.py, which needs the ofp module
import oftest.testutils
# Allow tests to import each other
sys.path.append(config["test_dir"])

# Handle optional positional arguments
test_specs = args 
if test_specs == []:
    test_specs = ["standard"]

test_modules = setup.load_test_modules()

# Check if test list is requested; display and exit if so
if config["list"]:
    setup.process_list_args(test_modules)

test_modules = setup.prune_tests(test_specs, test_modules, config["openflow_version"])

# Check if test list is requested; display and exit if so
if config["list_test_names"]:
    setup.process_list_test_names_args(test_modules)

# Sort test cases
sorted_tests = setup.sort_tests(test_modules)
if config["random_order"]:
    random.shuffle(sorted_tests)

for test in sorted_tests:
    suite.addTest(test())

# Allow platforms to import each other
sys.path.append(config["platform_dir"])

# Load the platform module
platform_name = config["platform"]
logging.info("Importing platform: " + platform_name)
platform_mod = None
try:
    platform_mod = imp.load_module(platform_name, *imp.find_module(platform_name, [config["platform_dir"]]))
except:
    logging.warn("Failed to import " + platform_name + " platform module")
    raise

try:
    platform_mod.platform_config_update(config)
except:
    logging.warn("Could not run platform host configuration")
    raise

if not config["port_map"]:
    setup.die("Interface port map was not defined by the platform. Exiting.")

logging.debug("Configuration: " + str(config))
logging.info("OF port map: " + str(config["port_map"]))

oftest.ofutils.default_timeout = config["default_timeout"]
oftest.ofutils.default_negative_timeout = config["default_negative_timeout"]
oftest.testutils.MINSIZE = config['minsize']

if config["random_seed"] is not None:
    logging.info("Random seed: %d" % config["random_seed"])
    random.seed(config["random_seed"])
else:
    # Generate random seed and report to log file
    seed = random.randrange(100000000)
    logging.info("Autogen random seed: %d" % seed)
    random.seed(seed)

# Remove python's signal handler which raises KeyboardError. Exiting from an
# exception waits for all threads to terminate which might not happen.
signal.signal(signal.SIGINT, signal.SIG_DFL)

if __name__ == "__main__":
    # Set up the dataplane
    oftest.dataplane_instance = oftest.dataplane.DataPlane(config)
    for of_port, ifname in config["port_map"].items():
        oftest.dataplane_instance.port_add(ifname, of_port)

    logging.info("*** TEST RUN START: " + time.asctime())
    if config["xunit"]:
        try:
            import xmlrunner  # fail-fast if module missing
        except ImportError as ex:
            oftest.dataplane_instance.kill()
            raise ex
        runner = xmlrunner.XMLTestRunner(output=config["xunit_dir"],
                                         outsuffix="",
                                         verbosity=2)
        result = runner.run(suite)
    else:
        result = unittest.TextTestRunner(verbosity=2).run(suite)
    setup.open_logfile('main')
    if oftest.testutils.skipped_test_count > 0:
        message = "Skipped %d test(s)" % oftest.testutils.skipped_test_count
        logging.info(message)
    logging.info("*** TEST RUN END  : %s", time.asctime())

    # Shutdown the dataplane
    oftest.dataplane_instance.kill()
    oftest.dataplane_instance = None

    if result.failures or result.errors:
        # exit(1) hangs sometimes
        os._exit(1)
    if oftest.testutils.skipped_test_count > 0 and config["fail_skipped"]:
        os._exit(1)
